application: simulation-modeling
version: 1
runtime: python
api_version: 1

handlers:
- url: /styles
  static_dir: styles
- url: /scripts
  static_dir: scripts
- url: /images
  static_dir: images
- url: /fancybox
  static_dir: fancybox
- url: /favicon.ico
  static_files: images/favicon.png
  upload: images/favicon.png
- url: /.*
  script: sm.py
